export enum BookingState {
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  APPROVAL_PENDING = 'APPROVAL_PENDING',
  CANCEL_PENDING = 'CANCEL_PENDING',
  CONFIRMED = 'CONFIRMED',
  REJECTED = 'REJECTED',
  // SAGA ERROR => Freeze booking
  FROZEN = 'FROZEN',
}
