export enum BookingState {
  IS_AVAILABLE_PENDING = 'IS_AVAILABLE_PENDING',

  PAYMENT_PENDING = 'PAYMENT_PENDING',
  REJECTED_PENDING = 'REJECTED_PENDING',

  CONFIRMATION_PENDING = 'CONFIRMATION_PENDING',
  CONFIRMED = 'CONFIRMED',

  REJECTED = 'REJECTED',

  // SAGA ERROR => Freeze booking
  FROZEN = 'FROZEN',
}
